modifier_value: 1.5
recoil_patterns:
  ALTERNATOR:
  - - 0.0
    - 14.4
    - 0.0109
  - - 0.0
    - 13.0
    - 0.0109
  - - 0.0
    - 15.8
    - 0.0109
  - - 0.0
    - 13.9
    - 0.0109
  - - 0.0
    - 15.6
    - 0.0109
  - - 0.0
    - 15.6
    - 0.0109
  - - -2.0
    - 12.7
    - 0.0109
  - - -2.0
    - 7.3
    - 0.0109
  - - -3.0
    - 13.2
    - 0.0109
  - - -3.0
    - 6.6
    - 0.0109
  - - -3.0
    - 9.8
    - 0.0109
  - - -2.0
    - 1.2
    - 0.0109
  - - -2.0
    - 6.8
    - 0.0109
  - - -2.0
    - 4.6
    - 0.0109
  - - -1.0
    - 10.0
    - 0.0109
  - - 0.0
    - 9.3
    - 0.0109
  - - 5.0
    - 3.2
    - 0.0109
  - - 5.0
    - 9.8
    - 0.0109
  - - 5.0
    - 0.7
    - 0.0109
  - - 5.0
    - 8.3
    - 0.0109
  - - 5.0
    - -0.2
    - 0.0109
  - - 5.0
    - 7.1
    - 0.0109
  - - 5.0
    - 1.7
    - 0.0109
  - - 5.0
    - 7.6
    - 0.0109
  - - 5.0
    - -0.7
    - 0.0109
  - - 5.0
    - 6.8
    - 0.0109
  - - 5.0
    - 0.0
    - 0.0109
  DEVOTION:
  - - 0.0
    - 0.0
    - 0.04
  - - 0.8
    - 24.5
    - 0.018
  - - 0.3
    - 20.0
    - 0.017
  - - 0.3
    - 23.5
    - 0.014
  - - 2.0
    - 23.2
    - 0.012
  - - 3.1
    - 19.5
    - 0.01
  - - 2.8
    - 12.6
    - 0.085
  - - 2.8
    - 10.6
    - 0.085
  - - 6.2
    - 4.8
    - 0.085
  - - 2.8
    - 6.4
    - 0.085
  - - 3.1
    - 5.8
    - 0.068
  - - 4.8
    - 7.1
    - 0.068
  - - 5.0
    - 4.4
    - 0.068
  - - 6.2
    - 2.3
    - 0.068
  - - 7.6
    - 1.8
    - 0.068
  - - 7.0
    - 0.5
    - 0.068
  - - 4.2
    - -1.6
    - 0.068
  - - 6.2
    - 1.6
    - 0.068
  - - -1.4
    - 4.6
    - 0.068
  - - 0.0
    - 5.3
    - 0.066
  - - -3.9
    - 3.9
    - 0.066
  - - -4.5
    - 2.3
    - 0.066
  - - -4.5
    - 2.5
    - 0.066
  - - -6.7
    - 3.0
    - 0.066
  - - -7.0
    - 3.0
    - 0.066
  - - -3.1
    - 3.2
    - 0.066
  - - 1.7
    - 3.7
    - 0.066
  - - -1.4
    - 4.8
    - 0.066
  - - -3.6
    - 4.4
    - 0.066
  - - -5.0
    - 3.5
    - 0.07
  - - -6.2
    - 2.1
    - 0.07
  - - -5.6
    - -0.5
    - 0.07
  - - -5.6
    - -0.5
    - 0.07
  - - -4.8
    - 3.7
    - 0.07
  - - -4.8
    - 3.7
    - 0.067
  - - -0.8
    - 4.1
    - 0.067
  - - -2.8
    - 3.5
    - 0.067
  - - 2.0
    - 3.5
    - 0.067
  - - 2.0
    - 3.5
    - 0.066
  - - -1.4
    - 3.7
    - 0.067
  - - -1.4
    - 2.8
    - 0.067
  - - -3.6
    - 1.6
    - 0.067
  - - -1.4
    - 2.3
    - 0.067
  - - 0.0
    - 3.0
    - 0.067
  - - 3.6
    - 1.8
    - 0.067
  - - -1.4
    - 2.3
    - 0.067
  - - 0.0
    - 3.0
    - 0.067
  - - 3.6
    - 1.8
    - 0.067
  FLATLINE:
  - - 0
    - 0
    - 0.0111
  - - 1.74
    - 17.0
    - 0.0111
  - - 9.86
    - 12.94
    - 0.0111
  - - 7.82
    - 9.52
    - 0.0111
  - - 5.0
    - 11.56
    - 0.0111
  - - -0.68
    - 8.84
    - 0.0111
  - - -2.04
    - 3.06
    - 0.0111
  - - -7.82
    - -4.42
    - 0.0111
  - - -4.76
    - -0.68
    - 0.0111
  - - -5.78
    - 4.76
    - 0.0111
  - - -4.06
    - 8.5
    - 0.0111
  - - 6.44
    - 3.74
    - 0.0111
  - - 13.6
    - 6.12
    - 0.0111
  - - 8.84
    - 3.74
    - 0.0111
  - - 12.24
    - -3.72
    - 0.0111
  - - 8.84
    - 3.76
    - 0.0111
  - - 8.02
    - 7.82
    - 0.0111
  - - 4.1
    - 5.52
    - 0.0111
  - - 3.04
    - 5.48
    - 0.0111
  - - -2.84
    - 3.7
    - 0.0111
  - - 4.76
    - 2.7
    - 0.0111
  - - -5.42
    - 3.4
    - 0.0111
  - - -8.16
    - 1.04
    - 0.0111
  - - -9.06
    - 2.72
    - 0.0111
  - - -13.12
    - 2
    - 0.0111
  - - -9.1
    - 2
    - 0.0113
  - - -8.8
    - 2
    - 0.0113
  - - 0
    - 2
    - 0.0113
  - - 0
    - 2
    - 0.0113
  - - 0
    - 2
    - 0.0113
  HAVOC:
  - - -6
    - 10
    - 0.089
  - - -6
    - 10
    - 0.089
  - - -6
    - 12
    - 0.089
  - - 0
    - 12
    - 0.089
  - - 0
    - 12
    - 0.089
  - - 4
    - 10
    - 0.089
  - - 4
    - 10
    - 0.089
  - - 4
    - 10
    - 0.089
  - - 4
    - 10
    - 0.089
  - - -4
    - 4
    - 0.089
  - - -4
    - 2
    - 0.089
  - - -4
    - 2
    - 0.089
  - - -4
    - 2
    - 0.089
  - - -4
    - 2
    - 0.089
  - - -2
    - 4
    - 0.089
  - - 4
    - 4
    - 0.089
  - - 4
    - 4
    - 0.089
  - - 4
    - 4
    - 0.089
  - - 4
    - 4
    - 0.089
  - - 4
    - 4
    - 0.089
  - - 4
    - 4
    - 0.089
  - - 4
    - 4
    - 0.089
  - - 4
    - 6
    - 0.089
  - - 4
    - 6
    - 0.089
  - - 4
    - 6
    - 0.089
  - - 4
    - 6
    - 0.089
  - - 4
    - 6
    - 0.089
  - - 4
    - 6
    - 0.089
  - - 4
    - 6
    - 0.089
  - - 4
    - 6
    - 0.089
  - - 0
    - 6
    - 0.089
  - - 0
    - 6
    - 0.089
  - - 0
    - 6
    - 0.089
  - - 0
    - 6
    - 0.089
  - - 0
    - 6
    - 0.089
  - - 0
    - 6
    - 0.089
  - - 0
    - 6
    - 0.089
  HEMLOK:
  - - 2
    - 8
    - 0.04
  - - 0
    - 8
    - 0.04
  - - 0
    - 8
    - 0.04
  L-STAR:
  - - 5
    - 5
    - 0.037
  - - 5
    - 5
    - 0.037
  - - 5
    - 5
    - 0.037
  - - 5
    - 5
    - 0.037
  - - 5
    - 5
    - 0.037
  - - 5
    - 5
    - 0.037
  - - 2
    - 5
    - 0.037
  - - 2
    - 5
    - 0.037
  - - 2
    - 5
    - 0.037
  - - 1
    - 2
    - 0.037
  - - 1
    - 2
    - 0.037
  - - -2
    - 2
    - 0.037
  - - -2
    - 2
    - 0.032
  - - -2
    - 2
    - 0.032
  - - -2
    - 5
    - 0.032
  - - -2
    - 5
    - 0.042
  - - -2
    - 5
    - 0.042
  - - -2
    - 5
    - 0.042
  - - -2
    - 5
    - 0.042
  - - -2
    - 5
    - 0.042
  - - -2
    - 5
    - 0.042
  - - -2
    - 5
    - 0.042
  - - -2
    - 5
    - 0.055
  - - -1
    - 5
    - 0.055
  - - -1
    - 5
    - 0.055
  - - -1
    - 5
    - 0.055
  - - -1
    - 5
    - 0.055
  - - -1
    - 5
    - 0.06
  - - -1
    - 5
    - 0.06
  - - -1
    - 5
    - 0.06
  - - -1
    - 5
    - 0.06
  - - -1
    - 5
    - 0.06
  - - -1
    - 5
    - 0.06
  - - 1
    - 5
    - 0.065
  - - 1
    - 5
    - 0.065
  - - 1
    - 5
    - 0.065
  - - 1
    - 5
    - 0.065
  - - 1
    - 5
    - 0.065
  - - 1
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  - - 0
    - 5
    - 0.065
  P2020:
  - - 2.4
    - 11
    - 0.013
  PROWLER:
  - - 2
    - 15.2
    - 0.01
  - - 2
    - 12.7
    - 0.084
  - - 2
    - 12.9
    - 0.084
  - - 2
    - 11.4
    - 0.084
  - - 3
    - 9.8
    - 0.084
  R-301:
  - - -3.5
    - 10.4
    - 0.08
  - - 4.4
    - 10.6
    - 0.08
  - - -6.4
    - 9.5
    - 0.08
  - - -1.2
    - 10.0
    - 0.08
  - - -5.3
    - 7.6
    - 0.08
  - - -0.4
    - 4.1
    - 0.08
  - - -1.8
    - 3.3
    - 0.08
  - - -4.1
    - 1.9
    - 0.08
  - - -2.4
    - 3.3
    - 0.08
  - - -3.2
    - 1.0
    - 0.08
  - - 0.0
    - 3.3
    - 0.08
  - - 2.0
    - 2.2
    - 0.08
  - - 5.0
    - 2.8
    - 0.08
  - - 4.7
    - 2.3
    - 0.08
  - - 5.0
    - 1.9
    - 0.08
  - - 5.2
    - 0.9
    - 0.08
  - - 3.2
    - 0.9
    - 0.08
  - - 0.0
    - 2.2
    - 0.08
  - - -1.1
    - 4.2
    - 0.08
  - - -3.1
    - 2.8
    - 0.08
  - - -3.6
    - 1.3
    - 0.08
  - - -3.6
    - 0.0
    - 0.08
  - - -2.6
    - 1.4
    - 0.08
  - - -2.4
    - 1.4
    - 0.08
  - - -3.0
    - 0.0
    - 0.08
  - - 0.0
    - 0.0
    - 0.08
  - - 0.0
    - 0.0
    - 0.08
  - - 0.0
    - 0.0
    - 0.08
  - - 0.0
    - 0.0
    - 0.08
  - - 0.0
    - 0.0
    - 0.08
  R-99:
  - - -1.6
    - 7
    - 0.053
  - - 0.1
    - 7.5
    - 0.053
  - - 2.3
    - 4.9
    - 0.053
  - - -1.8
    - 10
    - 0.053
  - - -3.3
    - 15.4
    - 0.053
  - - -6.3
    - 12
    - 0.053
  - - -5.5
    - 9.7
    - 0.053
  - - -2.5
    - 10.8
    - 0.053
  - - 0.2
    - 11
    - 0.052
  - - 2.3
    - 6.8
    - 0.052
  - - 4.5
    - 5.3
    - 0.052
  - - 0.9
    - 5.1
    - 0.052
  - - 1.6
    - 9.5
    - 0.052
  - - -1.1
    - 4
    - 0.052
  - - -4.9
    - 1
    - 0.052
  - - -2.3
    - 1.8
    - 0.052
  - - -4.5
    - 0.5
    - 0.052
  - - 4
    - 1.3
    - 0.052
  - - 0
    - 0
    - 0.052
  - - 2.5
    - 0.7
    - 0.052
  - - 3.5
    - 0.7
    - 0.052
  - - 4
    - 4
    - 0.052
  - - 3.5
    - 0
    - 0.052
  - - 4.6
    - 0
    - 0.052
  - - 2
    - 0
    - 0.052
  - - 2
    - 0
    - 0.052
  - - -5
    - -4
    - 0.052
  - - -5
    - 4
    - 0.052
  - - -5
    - -4
    - 0.052
  - - 0
    - 4
    - 0.052
  RAMPAGE:
  - - 0
    - 0
    - 0.018
  - - -2
    - 8
    - 0.018
  - - 6.6
    - 7.8
    - 0.018
  - - 3.2
    - 9.2
    - 0.018
  - - -4.8
    - 6.0
    - 0.018
  - - 0.7
    - 9.4
    - 0.018
  - - -5.3
    - 7.8
    - 0.018
  - - -5.2
    - 4.3
    - 0.018
  - - -5.4
    - 6.5
    - 0.018
  - - -5.2
    - 4.5
    - 0.018
  - - -1.3
    - 6.5
    - 0.018
  - - 6.7
    - 4
    - 0.018
  - - 7
    - 5
    - 0.018
  - - 3
    - 6.6
    - 0.018
  - - 5
    - 2.4
    - 0.018
  - - 5.5
    - 4
    - 0.018
  - - 4.5
    - 5
    - 0.018
  - - -1
    - 5.5
    - 0.018
  - - -2
    - 4.5
    - 0.018
  - - 2.3
    - 4
    - 0.018
  - - -3.5
    - 4
    - 0.018
  - - 2.7
    - 4
    - 0.018
  - - 3.5
    - 5
    - 0.018
  - - -2.2
    - 6
    - 0.018
  - - 3.7
    - 3.5
    - 0.018
  - - 4
    - 4.4
    - 0.018
  - - -3.5
    - 6.1
    - 0.018
  - - 5
    - 6
    - 0.018
  - - 4.8
    - 5
    - 0.018
  - - 4.7
    - 5.5
    - 0.018
  - - -1
    - 6.5
    - 0.018
  - - -3.5
    - 6
    - 0.018
  - - 3
    - 4
    - 0.018
  - - -3
    - 5
    - 0.018
  - - 6
    - 5.3
    - 0.018
  - - 3.5
    - 5
    - 0.018
  - - -1.5
    - 5.7
    - 0.018
  - - 2.5
    - 4
    - 0.018
  - - 4.5
    - 3
    - 0.018
  - - -3
    - 4.5
    - 0.018
  RE-45:
  - - -0.7
    - 12.6
    - 0.0112
  - - -1.4
    - 10.9
    - 0.0112
  - - -6.1
    - 11.2
    - 0.0112
  - - -3.0
    - 11.6
    - 0.0112
  - - -4.1
    - 9.9
    - 0.0112
  - - -6.7
    - 8.0
    - 0.0112
  - - -7.9
    - 7.1
    - 0.0112
  - - -7.7
    - 6.9
    - 0.0112
  - - -7.2
    - 6.2
    - 0.0112
  - - -9.7
    - 5.0
    - 0.0112
  - - -4.7
    - 5.1
    - 0.0112
  - - 0.0
    - 6.4
    - 0.0112
  - - -5.7
    - 5.7
    - 0.0112
  - - -3.4
    - 5.1
    - 0.0112
  - - -2.4
    - 6.4
    - 0.0112
  - - 2.4
    - 5.7
    - 0.0112
  - - -3.1
    - 4.7
    - 0.0142
  - - 0
    - 1.3
    - 0.0142
  - - 0
    - 3.4
    - 0.0147
  - - 0
    - 4.1
    - 0.0147
  - - 0
    - 2.4
    - 0.0147
  - - 0
    - 4.1
    - 0.0147
  - - 0
    - 0.0
    - 0.0147
  SPITFIRE:
  - - 3.0
    - 18.2
    - 0.011
  - - 1.5
    - 4.8
    - 0.011
  - - 9.6
    - 9.6
    - 0.011
  - - 6.3
    - 7.0
    - 0.011
  - - 3.3
    - 6.2
    - 0.011
  - - -0.3
    - 9.2
    - 0.011
  - - -4.5
    - 2.6
    - 0.011
  - - -9.6
    - -2.0
    - 0.011
  - - -2.7
    - -1.6
    - 0.011
  - - -3.9
    - 3.2
    - 0.011
  - - -2.7
    - 6.6
    - 0.011
  - - 4.5
    - 2.0
    - 0.011
  - - 9.9
    - 4.4
    - 0.011
  - - 5.1
    - 1.4
    - 0.011
  - - 9.6
    - -1.6
    - 0.011
  - - 4.2
    - 1.4
    - 0.011
  - - 1.8
    - 7.8
    - 0.011
  - - 3.3
    - 7.6
    - 0.011
  - - 6.9
    - 4.4
    - 0.011
  - - 9.0
    - 1.8
    - 0.011
  - - 3.9
    - 0.6
    - 0.0113
  - - -1.2
    - 5
    - 0.0113
  - - -6.9
    - 2.5
    - 0.0113
  - - -4.5
    - 2
    - 0.0113
  - - -7.8
    - 2.2
    - 0.0113
  - - -8.1
    - 1
    - 0.0113
  - - -7.8
    - -1
    - 0.0113
  - - -3.3
    - 3.6
    - 0.0113
  - - -4.5
    - 4.2
    - 0.0113
  - - -0.3
    - 4.2
    - 0.0113
  - - -9.6
    - -2.0
    - 0.0113
  - - -2.7
    - -1.6
    - 0.0113
  - - -3.9
    - 2.2
    - 0.0113
  - - -2.6
    - 3
    - 0.0113
  - - 4.5
    - 1.5
    - 0.0113
  - - 9.9
    - 3.4
    - 0.0113
  - - 5.1
    - 1.4
    - 0.0113
  - - 9.6
    - -1.6
    - 0.0113
  - - 4.2
    - 1.4
    - 0.0113
  - - 1.8
    - 7.8
    - 0.0113
  - - 3.3
    - 7.6
    - 0.0113
  - - 6.9
    - 4.4
    - 0.0113
  - - 9.0
    - 1.8
    - 0.0113
  - - 3.9
    - 0.6
    - 0.0113
  - - -1.2
    - 5.6
    - 0.0113
  - - -6.9
    - 3.2
    - 0.0113
  - - -4.5
    - 2.6
    - 0.0113
  - - -7.8
    - 3.2
    - 0.0113
  - - -8.1
    - 2.0
    - 0.0113
  - - -7.8
    - -2.0
    - 0.0113
  - - -3.3
    - 4.6
    - 0.0113
  - - -4.5
    - 6.2
    - 0.0113
  - - -0.3
    - 6.2
    - 0.0113
  - - -9.6
    - -2.0
    - 0.0113
  - - -2.7
    - -1.6
    - 0.0113
  - - -3.9
    - 3.2
    - 0.0113
  - - -2.7
    - 6.6
    - 0.0113
  - - 4.5
    - 2.0
    - 0.0113
  - - 9.9
    - 4.4
    - 0.0113
  - - 5.1
    - 1.4
    - 0.0113
  - - 9.6
    - -1.6
    - 0.0113
  VOLT:
  - - 0.0
    - 12.9
    - 0.081
  - - 0.0
    - 9.5
    - 0.081
  - - -1.5
    - 11.3
    - 0.081
  - - -1.7
    - 9.4
    - 0.081
  - - -1.7
    - 11.1
    - 0.081
  - - -2.5
    - 13.1
    - 0.081
  - - -2.5
    - 9.7
    - 0.081
  - - -2
    - 9.8
    - 0.081
  - - -2.5
    - 9.2
    - 0.081
  - - -2.0
    - 6.6
    - 0.081
  - - 1.0
    - 5.8
    - 0.081
  - - 2.7
    - 1.2
    - 0.081
  - - 4.0
    - 6.8
    - 0.081
  - - 6.0
    - 4
    - 0.081
  - - 5.0
    - 3.0
    - 0.081
  - - 5.0
    - 3.3
    - 0.081
  - - 0.0
    - 1.2
    - 0.081
  - - -2.0
    - 1.8
    - 0.081
  - - -2.0
    - 1.7
    - 0.081
  - - -2.0
    - 5.3
    - 0.081
  - - 3.0
    - 0
    - 0.081
  - - 1
    - 0.0
    - 0.081
  - - 1
    - 7.0
    - 0.081
  - - 1
    - 0.0
    - 0.081
  - - 1
    - 0.0
    - 0.081
  - - 1
    - 0.0
    - 0.081
  - - 1
    - 0.0
    - 0.081
scan_coord_one:
  height: 25
  left: 1555
  top: 1030
  width: 110
scan_coord_two:
  height: 25
  left: 1715
  top: 1030
  width: 110
